### ISSUE TITLE
error executing star() function

### ISSUE THREAD

**Issue by Lum1nus** [jckantor/Siemens-Star#1]
<ipython-input-3-0628f997d8a4> in star(xc, yc, radius, cycles, colors, clines)
     13     fmt = fmt.format(*xy) + ' style="fill:{0}" transform="rotate({1:.3f},{2:.3f},{3:.3f})"/>'
     14     strn = '\n'.join([fmt.format(colors[k],360.0*(n+float(k)/len(colors))/cycles,xc,yc) 
---> 15                      for n in range(0,cycles) for k in range(0,len(colors))]) + '\n'
     16     if clines:
     17         clist = []

TypeError: 'float' object cannot be interpreted as an integer

**Comment by jckantor** [comment]
Thanks for the check.  Error has been fixed, and documentation modified to include an example of the resulting graphic.
